sass/node-sass

lib/render.js, test/cli.js, test/fixtures/output-directory/index.scss
Pull Request for #574 .
Changes are on 'output-directory' branch.
:)
=> Output directory is created if it doesn't exists. 

bin/node-sass, lib/index.js, lib/render.js, scripts/build.js, src/binding.cpp, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h, test/api.js, test/fixtures/extras/my_custom_importer_file.js, test/fixtures/source-map/expected.map
* Fixes the async crashing by explicitly
closing async.
* Changes the behavior of renderSync importer
* Updates index accordingly.
* Removes obsolete tests accordingly.
BIG THANKS to @txdv and this addresses #586 ! :tada::+1:
**Need to update the docs accordingly.**
---
Code: Adds NanScope() to guard nan handlers.
* Fixes for Persistent.
* Credit @kkoopa (thanks for pointing these out!).
=> Importer: General overhauling

README.md
Very small PR that adds the fact that you must specify `outFile` as well in order to generate a source map.
=> Add clarity to sourceMap option

README.md, scripts/build.js, scripts/install.js
Install: Improves code to get proxy.
* Credit: @xzyfer.
* Addresses #588.
---
Build: Use grep to filter test cases.
* Uses different strategy to test binary.
* Test two cases and declare the binary OK.
Issue URL: #611.
=> Build related fixes

appveyor.yml
Duh! AppVeyor doesn't support NJS v0.10.35 [yet](https://github.com/appveyor/ci/issues/99) ..
=> Appveyor: Make nodejs versions flexible

lib/index.js, src/binding.cpp, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h
* Importer: Drops `uv_mutex` in favor of `std::mutex`. (0720fa8)
* It is not safe to use `uv_cond_wait`
outside of v8 thread (`uv loop`).
* Importer: Hack to make CLI importer usage work. (ff53926)
* If anyone could ever explain this!
* This is related to the changes made in 0720fa8.
* **Tidbit:** it was also failing on windows with node.js v0.10.32
updating to v0.10.35 (current stable), it worked without this hack on Windows
but when tested with v0.10.35 on Ubuntu via nvm, it still fails without this hack.
The only downside of this hack is extra nuisance on console
(I tried to dodge it by overriding `console.log` function, but that didn't work either, so we would have to live with this *little annoyance*<b>**</b>, until someone can figure out why it is happening).
@browniefed, @xzyfer, …
=>  Importer: Drops uv_mutex in favor of std::mutex 

package.json, scripts/install.js
=> Install: Use npmconf to get proxy config

bin/node-sass, package.json
The watcher is broken. So very broken. Two major problems with it
- it compiles files starting with underscores (`_`) which is a big no-no
- it has no awareness of the the import graph
Assuming the following directory structure
```
src
|--foo.scss
|--bar.scss
|-- components
|-- _baz.scss
```
where 'foo.scss` and `bar.scss`, and running the following command `node-sass -w -r --output dist src`.
A modification to `src/components/_baz.scss` **should not** compile `_baz.scss`. It **should** traverse the import graph and compile `dist/foo.css` and `dist/bar.css`.
This is how the native sass watcher works.
Use [sass-graph](https://github.com/xzyfer/sass-graph) to build an in memory graph of the `@imports` to determine the correct compilation targets for a modified file.
I believe this is the …
=> Use sass-graph for accurate sass watching

package.json, src/binding.cpp
This allows node-sass to build on iojs. Tests suite passes with iojs 1.0.1 and node.js 0.10.31.  Are there other node versions that should be tested as well?
Addresses https://github.com/sass/node-sass/issues/627.
One thing to note when manually rebuilding is that upstream node-gyp doesn't yet support iojs, so you need to make sure you're building using node-gyp bundled with iojs: https://github.com/iojs/io.js/issues/433
=> iojs support

bin/node-sass
If the user specified to watch a directory/file and an error occurs we shouldn't stop the process.
=> Don't exit if an error occurs while watching

lib/index.js, lib/utils.js, package.json, scripts/build.js, scripts/install.js
The new format is:
`{platform}-{arch}-{runtime}-{major.minor}`
where `major` and `minor` version belong to
the runtime.
Related Issue: #655.
//cc @xzyfer
=> Build: Produces identifiable binary name

src/sass_context_wrapper.h
The C malloc() functions require inclusion of ``stdlib.h``
This fixes compilation on FreeBSD.
=> Include correct header for malloc related functions.

scripts/install.js
The main goal of this PR is to solve an error. When there are some kind of errors downloading the binary file (network errors mostly) the file where it was going to be downloaded to is not unlinked and left as an empty file and then the build script "thinks" that the download went ok and does not do the manual build. I changed the code to create the file just when it is necessary.
=> Improve install script

README.md, appveyor.yml, lib/extensions.js, lib/index.js, scripts/build.js, src/binding.cpp
* README: Removes v0.11 workaround section
* Reason: njs v0.11 is not relavent any more.
* Solution: Update to node v0.12 with which<br />
node-sass v2.0.1 is compatible OOTB.
* CI: Updates io.js to 1.2 for AppVeyor.
* Code: Throws `Error` object.
* Returns json-string error from LibSass as is.
* Extends empty error object with parsed JSON.<br/>
Note: The reason why [`NanError`](https://github.com/rvagg/nan#nanerrormessage-nantypeerrormessage-nanrangeerrormessage) is not used<br />because LibSass returns error as JSON<br /> string with `message` as member, so we would<br/> have to reparse and reassign the obj in that case.<br/>Issue URL: #675.
* README: Updates error info. (related to previous commit)
* Code: Uses more C++ style nomenclature. 
* Code: Resolves symbolic link.  <br/>On …
=> Misc. Fixes

README.md, lib/index.js, test/api.js
Replaces #681 (single focused commit based on sass/node-sass@master)
This patch and tests introduces a context for all callbacks currently
in node-sass. Right now, they run w/ an ambiguous context, making the
`this` keyword not helpful to importer developers (and eventually
custom function developers). This creates a context object, adds the
render options to said context object, and then uses that context for
importer, success, and error callbacks via `this.options`.
By using a context instead of just `.call(options...)` there is a hook
for later should we find additional environmental information is
valuable to importer / custom function developers such as the node
environment, node-sass version, etc.
Additionally, info() is exposed in the context so any node modules
imported would be …
=> Render options in callbacks as this.options

lib/extensions.js, package.json
The new binary path format is: 
`<platform>-<arch>-<v8 version>/binding.node`
Issue URL: #694.
=> Build: Uses v8 version instead of runtime name.

README.md, bin/node-sass, lib/render.js, package.json, test/cli.js
When no destination or output folder is provided,
it will print the output to stdout.
If the source-map option was set, it will print
it as well.
Issue URL: #669.
PR URL: #701.
//cc @xzyfer
=> CLI: Retires stdout option

README.md, lib/index.js, test/api.js
This is node-style callbacks for #676. This allows us to release the new callback style without introducing backwards incompatible changes. If a node style callback is provided, it will be used. For now, this stacks with the original `options.success` and `options.error`, although it can be trivially changed to an xor.
To highlight the new interface, a separate `describe` was added to the tests which identifies the `{options}, cb` interface and tests it independently.
=> Adding a backwards compatible node-style callback

.jshintignore, bin/node-sass, lib/extensions.js, lib/index.js, lib/render.js, package.json, scripts/build.js, scripts/install.js, test/api.js, test/cli.js, test/fixtures/extras/my_custom_importer_data.js, test/fixtures/extras/my_custom_importer_data_cb.js, test/fixtures/extras/my_custom_importer_file.js, test/fixtures/extras/my_custom_importer_file_and_data.js, test/fixtures/extras/my_custom_importer_file_and_data_cb.js, test/fixtures/extras/my_custom_importer_file_cb.js, test/spec.js
* Code: Formats and fixes JSCS warnings. …  
* Removes unused pacakge `shelljs`.
* Fixes package.json validation issue reported
by WE2013, based on njs package.json schema:
> *The value property "repository" must be of
type "Object", but was "sass/node-sass"*
* Repo: Adds .jshintignore.
* To avoid validating node_modules directory.
=> Code: Formats and fixes JSCS warnings

README.md, lib/index.js, lib/render.js, test/api.js, test/spec.js
WIP
This change removes the object hash success/error callbacks in
favor of node style callbacks. This includes README and test
updates, including the removal of two tests that are now
obsolete.
This also updates the CLI code pathway to use the node style
callback.
BREAKING API CHANGE
This removes the success/error option keys as ways to register
callbacks into node-sass. Instead, a function should be passed as
the second parameter for the asyncronous `render` call. It takes
a standard node signature of `error, callback`.
=> Removal of option hashed based success and error callbacks

README.md
This improves the option documentation for #672 and adds the default
information gleaned from the `getOptions` functions and their defaults
from the prior README.md
=> Better default values in the README.md file

README.md, lib/render.js, src/binding.cpp, test/api.js, test/spec.js
* CSS and Map is casted as Buffer from binding.<br/>
Advantages:
* Buffers are super fast.
* User can write them to file as is.
* User can forward to response stream as is.
* User can convert the result it to string as is:
* `result.css.toString()`
* `result.map.toString()` or<br/>
`JSON.stringify(result.map)`
* Updates tests and CLI usage accordingly.
* Updates README to reflect the changes.
Issue URL: #711.
PR URL: #729.
//cc @joliss, @xzyfer, @kevva
=> API: Returns result as `Buffer`s not string

scripts/upload.js
This is first in the series of overhauling build steps. Find the related discussion at: https://github.com/sass/node-sass/issues/712.
The public access token can be generated from: https://github.com/settings/applications#personal-access-tokens.
Anyone with write-access to sass/node-sass can run:
> node scripts/upload --auth MyGitHubOAuthToken
This will upload the binary file to the latest release (for instance, current is v2.0.1).
To upload the asset to specific release:
> node scripts/upload --auth MyGitHubOAuthToken --tag 2.0.0
To upload the asset from a custom paths:
> node scripts/upload --auth MyGitHubOAuthToken --path ~/docs/my_emails/someoneITrust/blah.node
//cc @nschonni, @xzyfer
=> Build: Implements GH API to upload binaries

package.json, scripts/coverage.js
Bumps mocha to 2.2.1, and fixes the error highlighted in https://github.com/mochajs/mocha/issues/1585:
```
0.80s$ npm run-script coverage
> node-sass@2.0.1 coverage /home/travis/build/sass/node-sass
> node scripts/coverage.js
/home/travis/build/sass/node-sass/node_modules/.bin/_mocha: 1: /home/travis/build/sass/node-sass/node_modules/.bin/_mocha: /bin: Permission denied
npm ERR! node-sass@2.0.1 coverage: `node scripts/coverage.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@2.0.1 coverage script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/coverage.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! …
```
=> Update process spawning in coverage.js for mocha 2.2.x

bin/node-sass, test/cli.js
* Removes input file parameter from watch test.
* Uses `once` instead of `on` in CLI tests.
* Removes `bin.kill` in favour of `once`.
Issue URL: #755.
=> CLI: Do not require input file on watch

binding.gyp, libsass.gyp, scripts/build.js, src/sass_context_wrapper.h
If PKGCONFIG is set to YES in the proces
environment, use pkg-config to locate
system libsass to be linked.
This way there is no need to checkout
a src/libsass submodule at all and
the library from the package management
system can be used.
Otherwise fallback to the bundled libsass.
By default, use the bundled library.
PR: #139
PR: #389
PR: #744
=> Build with the unbundled libsass

README.md, bin/node-sass, lib/index.js, lib/render.js, src/binding.cpp, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h, test/api.js, test/cli.js
* `indentType` can be space or tab.
* default: space.
* `indentWidth` is a positive integer.
* default: 2.
* maximum: 10
* `linefeed` could be:
* cr
* crlf
* lf
* lfcr
Issue URL: #682.
=> Feature: Configurable linefeed and indent

binding.gyp, package.json, scripts/build.js, src/custom_function_bridge.cpp, src/custom_function_bridge.h, src/custom_importer_bridge.cpp, src/custom_importer_bridge.h, src/sass_context_wrapper.h, src/sass_types/boolean.cpp, src/sass_types/boolean.h, src/sass_types/color.cpp, src/sass_types/color.h, src/sass_types/error.cpp, src/sass_types/error.h, src/sass_types/factory.cpp, src/sass_types/factory.h, src/sass_types/list.cpp, src/sass_types/list.h, src/sass_types/map.cpp, src/sass_types/map.h, src/sass_types/null.cpp, src/sass_types/null.h, src/sass_types/number.cpp, src/sass_types/number.h, src/sass_types/sass_value_wrapper.h, src/sass_types/string.cpp, src/sass_types/string.h, src/sass_types/value.h
Minor cleanup; removing redundant headers
from `.cpp` files.
Based on: https://github.com/sass/node-sass/pull/763#issuecomment-86293997.
=> Code: Reverted #763

README.md, bin/node-sass, lib/render.js, src/binding.cpp, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h, test/api.js, test/cli.js
Related discussions: https://github.com/sass/node-sass/issues/731 & https://github.com/sass/libsass/issues/908.
//cc @itsnydell and @joliss
According to the [source-map v3 docs](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#):
> (sourceRoot is) An optional source root, useful for relocating source files on a server or removing repeated values in the “sources” entry.  This value is prepended to the individual entries in the “source” field.
Further it goes:
> **Resolving Sources**
If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).
Therefore, node-sass will pass the value of `sourceMapRoot` (or `source-map-root`) to the …
=> Feature: Provides sourceMapRoot option

README.md, bin/node-sass, lib/render.js, test/cli.js, test/fixtures/custom-functions/setter-expected.css, test/fixtures/custom-functions/setter.scss, test/fixtures/custom-functions/string-conversion-expected.css, test/fixtures/custom-functions/string-conversion.scss, test/fixtures/extras/my_custom_functions_setter.js, test/fixtures/extras/my_custom_functions_string_conversion.js
* Adds related tests and fixtures.
Issue URL: #784.
=> CLI: Adds support for Custom Functions

bin/node-sass, test/cli.js, test/fixtures/watching/foo.scss, test/fixtures/watching/index.scss
This fixes #781.  Using the watch command now finds all of the dependencies and will recompile when one of them changes.
=> Fixed watch behavior

src/binding.cpp, src/custom_importer_bridge.cpp
Lets the error propagate to libsass.
This goes against the concept of fast aborting,
but this way downstream user will not get a blunt
exception, but receive a well-formatted JSON
error.
Note: this exception from importer callback's
post-process handler cannot be captured by try-
catch.
The edit in binding.cpp is also required, because
those conditions will never get satisfied anyway.
Removed due to aforementioned reasons.
=> Code: Don't throw from interim callback state

lib/index.js
This was reported at https://github.com/sindresorhus/grunt-sass/issues/203. It is an edge case, if user is already using `outFile` option with `sourceMap: true`, the exception will not be thrown.
=> Code: Skips path.resolve when outFile is not set

README.md, bin/node-sass, package.json, test/cli.js, test/fixtures/input-directory/sass/_skipped.scss, test/fixtures/input-directory/sass/nested/three.scss, test/fixtures/input-directory/sass/one.scss, test/fixtures/input-directory/sass/two.scss
As per #828 - Adds the ability to compile multiple files from a directory.
Given this structure:
```
- sass/
| - main.scss
|  | - components/
|  |  | - _component1.scss
|  | - pages/
|  |  | - page1.scss
|  |  | - page2.scss
```
If you run: `node-sass sass/ -o build/`, you would get this output:
```
- sass/
- build/
| - main.css
|  | - pages/
|  |  | - page1.css
|  |  | - page2.css
```
Skips files that start with an `_`. Also respects the current `--recursive` flag. So given the same structure as above, if you ran `node-sass sass/ -o build/ --recursive false`, you would get:
```
- sass/
- build/
| - main.css
```
- Throws an error if you don't difine `--output`
- Throws an error if `--output` isn't a directory
- If `--output` is defined, but the folder doesn't exist, it will create it. …
=> CLI: Adds support for multi-file compilation.

README.md
It's time for a change! :bulb: 
I have learned a lot and gained technical as well as administrative experience from this project. And once again thanks to @andrew for [extending me this opportunity](https://github.com/sass/node-sass/pull/549). I haven't used sass/node-sass for quite sometime in my day job or personal projects. Unfortunately, my job is keeping me busy and I am unable to invest more time into maintaining node-sass.
@xzyfer, has not only not only hands on the internals of node-sass, but also have better understanding of underlying libsass and node.js in general. He is also very active in Sass and CSS communities. Above all, he uses node-sass on daily basis. 
So ladies and gents, the active team lead of node-sass is Michael Mifsud (@xzyfer). :tada: :sparkler: :sunglasses: …
=> Admin: Promoting Michael Mifsud to project lead

README.md, bin/node-sass, test/cli.js, test/fixtures/invalid/index.scss
Don't want to step on toes here if you were already working on this, @gibatronic , but thought I'd take a stab at implementing the `-q, --quiet` flag for the cli. 
I think this addresses the use case of #841 
Wrote some tests to ensure that the flag keeps the cli from outputting to `stderr` on `log` and `warn`. Also wrote a test to ensure that `error` is still passed through, regardless of if `--quiet` is used by creating an `invalid` fixture which contains a reference to an undefined sass variable. 
@gibatronic would this successfully enable you to do what you need to do?
/cc @am11 @wesleytodd
=> CLI: Adds --quiet flag

scripts/build.js, scripts/git.sh
This PR fixes npm installs via git urls erring when building the bindings.
When developing on node-sass I often npm install dev branches into my production code to test for regression or other issues. At the moment this require checking in the `src/libsass` directory, then rebasing that commit out when creating a PR.
This PR makes it so the libsass submodule is checked out as part of the postinstall process. The version checked out denoted by the existing `package.libsass` flag.
/cc @am11
=> Check libSass submodule when npm installing via git url

scripts/build.js
This PR fixes an issue with the build script's git submodule init. Originally reported https://github.com/sass/node-sass/pull/874#issuecomment-94421659.
=> Fix bug with join defaulting to comma separator

scripts/build.js, scripts/git.sh
This PR is an iteration in the build script's git fallback introduced in #874.
We're now executing the git operations purely from JS - no more shell script - because we <3 Windows.
=> Handle build script git operations in JS

test/cli.js
After running npm test four node processes
keep on running:
85880  1  S        0:00,41 node node-sass/bin/node-sass --watch node-sass/test/fixtures/simple/tmp.scss
85883  1  S        0:00,41 node node-sass/bin/node-sass --watch --quiet node-sass/test/fixtures/simple/tmp.scss
85885  1  S        0:00,40 node node-sass/bin/node-sass --output-style compressed --watch node-sass/test/fixtures/simple/bar.scss
85888  1  S        0:00,42 node node-sass/bin/node-sass --output-style compressed --watch node-sass/test/fixtures/watching/index.scss
We need to explicitly kill them when the test is done.
=> Kill watcher processes during test

scripts/install.js
This PR implements with #836 with a minor clean up, and merge conflicts resolved.
Upon installation when fetching the binary we'll use a node-sass specific `User-Agent` header.
/cc @saper
=> Set User-Agent: HTTP header

README.md, binding.gyp, lib/extensions.js, lib/index.js, src/binding.cpp, src/libsass.gyp, test/api.js
Return real libsass version
information - in when a shared library
is used this version may be changed
even without recompilation
libsass version in the package.json
file is now used only for checking
out the bundled libsass library
from the git submodule
PR: #912
=> Fix #912: Use runtime libsass version

scripts/build.js
This PR updates the build script to respect the LIBSASS_EXT build flag when falling back to git. Originally suggested in https://github.com/sass/node-sass/pull/876#issuecomment-94730030
@saper does this suit your usecase?
=> Respect the LIBSASS_EXT build flag when falling back to git

CONTRIBUTING.md, README.md, TROUBLESHOOTING.md
This PR introduces a basic troubleshooting guide for common issues.
This will give us a common places to link people to from issues, and single point of reference for debugging information.
I don't by any means expect this to be perfect right off the bat, but we need start somewhere.
Fixes #916.
/cc @am11 @saper
=> Create a troubleshooting guide

package.json
Currently when traversing the import graph we do not respect the behaviour of checking the current working directory first. This can result in the wrong files being compiled if there are naming collisions.
This was fixed upstream in sass-graph@2.0.0
Fixes #905.
=> Watcher should prioritize cwd when resolving imports

binding.gyp, package.json
Before building, first apply the following patch
to pangyp: rvagg/pangyp#5 (until it is merged).
Issue URL: #870.
=> build: Adds win_delay_hook so iojs runs with alias

lib/extensions.js, lib/index.js, scripts/install.js
`package` is a reserved word in strict mode. Therefore, node-sass cannot be packaged by a bundler that forces strict mode.
This pull request removes the `package` keyword, and renames the variable to `pkg`, as it is in `scripts/build.js`.
=> Remove use of 'package' as a variable name in install.js

package.json
This PR loads `am11/pangyp` fork from HTTPS rather than git.
This is an alternative to https://github.com/sass/node-sass/pull/942 based on #931 which may or may not work.
Fixes #939.
Fixes #933.
Closed #931.
Closed #942.
=> Load am11/pangyp from HTTPS

package.json
This PR switches node-sass back to official pangyp now that https://github.com/rvagg/pangyp/pull/5 is in stable.
/cc @am11 @saper
=> Switch back to official pangyp

bin/node-sass
When doing `node_modules/.bin/node-sass --help`, the "Usage" text didn't mention options in the stdin/stdout syntax, but they are there. The example uses them.
This adds a mention of options to the help text.
=> --help fix: mentioning options also in stdin/stdout syntax

bin/node-sass, test/cli.js, test/fixtures/watching-dir/index.scss
Fixing watch behavior for full directory. Currently barks on glob pattern in filename.
=> Fix ability to watch whole directory

README.md, bin/node-sass, lib/render.js, test/cli.js
* For multi-file compilation.
* Written test.
* Usage:
```javascript
node-sass --source-map source-map/dir --output css/path style/src/
```
Issue URL: #903.
PR URL: #964.
=> CLI: Adds source-map=directory support

lib/render.js, test/cli.js
Due to object passed by reference
closes https://github.com/sass/node-sass/issues/967
Possibly conflicting change with https://github.com/sass/node-sass/pull/964 I'll rebase when sourcemap support will be merged
=> Fix multi-file compile only writes to the last path when multiple files import a changed partial

package.json
- Fixed multi-file compilation sometimes writing to wrong file (#967, @kkopachev)
- Fixed multi-file compilation missing source maps (#903, @am11)
>The source-map option accepts `true` as value, in which case it replaces destination extension with `.css.map`. It also accepts path to `.map` file and even path to the desired directory. In case of multi-file compilation path to `.map` yields error.
=> Release v3.1.2

package.json
This PR bumps Libsass to 3.2.5.
=> Bump Libsass to 3.2.5

package.json
This PR tracks the 3.2.0 release.
```
- Updated Libsass to 3.2.5 (@xzyfer, #992)
```
=> Release 3.2.0

README.md
JavaScript's typeof operator returns "string" not "String" for string values and objects
=> Correct typeof reference in README

TROUBLESHOOTING.md, package.json
* dad5d6a - Package: Updates dependencies.
* 9f53ee8 - Docs: Removes obsolete note for io.js on Windows.
* The issue was fixed by rvagg/pangyp#5 and shipped with pangyp v2.0.
* 705f01e - Docs: Adds gotcha for VS2015 task runner. (as per https://github.com/sass/node-sass/issues/532#issuecomment-120557709)
* Updates troubleshooting guide.
/cc @xzyfer (after the review, I can squash the commits before merging if necessary)
=> Misc. updates

appveyor.yml
There might be issues with running npm under PS,
therefore let's run npm under CMD.
https://github.com/sass/node-sass/issues/996
http://help.appveyor.com/discussions/problems/2347-npm-275prefer-global-warning-causes-failure-command-executed-with-exception#comment_37223989
https://github.com/npm/npm/issues/8517
Effectively reverts: https://github.com/sass/node-sass/pull/995
=> Don't launch npm in the PowerShell

lib/extensions.js
Some private npm repositiories seem not to carry
custom package.json properties around.
Fixes: #1030
=> Provide nodeSassConfig hardcoded defaults

bin/node-sass, test/cli.js, test/fixtures/watching/bar.sass, test/fixtures/watching/index.sass
This fixes a bug that prevented the watcher from triggering file compilations on changes to .sass file.
Fixes #1075
=> The watch should watch indented syntax files too

README.md
Added note to indentedSyntax in read.me to clarify that node-sass can compile mixed libraries even with this set to false.
=> Added note to indentedSyntax in read.me 

test/api.js
=> Additional tests for SassTypes::Color

.gitignore, .jshintignore, package.json, scripts/coverage.js, test/spec.js
1) Use istanbul instead of jscoverage
2) generate nice HTML report with branches
3) include 'spec.js' tests in the coverage reporting - hits/line ratio on index.js ~300
4) show little coverage summary in the console output
5) do not use spawn and shell to launch mocha and coveralls clients - wire reporters directly via JavaScript
=> Rework test coverage facility w/ istanbul

.travis.yml
Seems like we didn't catch serious failures reported by Travis CI on after #1058. Make io.js 3.0 compliance mandatory now.
=> Make Travis CI to report failures on io.js 3.0

src/sass_types/sass_value_wrapper.h
In case of exception occuring during construction
of a Sass type instance just return Undefined value,
as the delayed JS exception will pop up later.
The following code:
var sass = require('./');
sass.render({
data: 'div { color: foo(); }',
functions: {
'foo()': function() {
return sass.types.Color(2,3);
}
}
});
now results in an libsass error
Constructor should be invoked with either 0, 1, 3 or 4 arguments
instead of V8 abort
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal
Fixes https://github.com/sass/node-sass/issues/1090
=> Handle MaybeLocal value from the constructor

.travis.yml
This PR updates our travis ci config to be more explicit about which runtime versions to run. 
It also makes sure we're running tests against all supported runtime versions.
=> Be explicit about which runtime versions travis should test

appveyor.yml, package.json
* CI: Adds explicit runtime versions in job matrix.
Updates appveyor.yml.
Related: #1096
* CI: Stores build artifact (binding.node) for job. 
* The artifact will be available under job details in `Artifacts` tab
* URL format: `https://ci.appveyor.com/project/sass/node-sass/build/<build-id>/job/<job-id>/artifacts`
* Package: Updates to latest versions.
=> CI: Adds explicit runtime versions in job matrix

.travis.yml, appveyor.yml
To speed up a build and avoid bombarding
nodejs.org and iojs.org with connections we should
cache what we download via npm and node-gyp.
Note: %AppData% [does not seem to presently work](https://help.appveyor.com/discussions/problems/2869-appdata-causes-error-parsing-appveyoryml-while-scanning-for-the-next-token-find-character-that-cannot-start-any-token) there.
Related:
https://github.com/nodejs/nodejs.org/issues/167
https://help.appveyor.com/discussions/problems/2849-intermittently-unable-to-connect-to-nodejsorg
=> Use build cache for NPM and GYP files

scripts/build.js
`node-gyp` is using `process.config.target_defaults.default_configuration`
to check which configuration is about to be used, but this
can be overriden by particular engine's `config.gypi` file.
Since we do not support such a cross compilation anyway,
use this variable in place of a hardcoded default.
Instead of introducing another option to force the use
of 'Release' we should read and pass options to node-gyp.
This is not implemented here.
Fixes https://github.com/sass/node-sass/issues/1077
=> Use process.config.target_defaults.default_configuration as the build type default

package.json
`fsevents@0.3.8` introduces a segfault that manifests when used with node-sass https://github.com/strongloop/fsevents/issues/82
`fsevents` is widely popular. As a mitigation we've added `fsevents@0.3.7` as an `optionalDependency`. The intention here is the prevent users install `node-sass@3.3.x` and `fsevents@0.3.8` by using npm's deduping behaviour.
Adding `optionalDependency` will cause npm to dedupe the package and install the most suitable version. Since we've pinned to a specific version ours will always be the most suitable.
This is certainly cause us problems in the long run and should be reverted as soon as issue fixed upstream.
=> Workaround the segfault that occurs when used with fsevents

binding.gyp, src/binding.cpp, src/callback_bridge.h, src/custom_function_bridge.cpp, src/custom_function_bridge.h, src/custom_importer_bridge.cpp, src/custom_importer_bridge.h, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h
libsass needs to be linked against libc++ from clang
on MacOSX to use advanced C++11 functions.
The binding code is not that picky and we can try
to link against whatever is the default.
Mixing C++ runtime libraries is still very bad, but
we should be able to avoid crash when being
used with another node module using nan.h
and its GetWrapper() static cache:
https://github.com/strongloop/fsevents/issues/82
=> Use libstdc++.so.6.0.9 to workaround static init problems

package.json
This reverts commit 3166b613fd17f1182e99a9e46fd9e355d3dfb8e1.
Not needed any more after update to nan 2.0.8 and
enabling the use of libstdc++.so.6 for the binding.
=> Revert "Workaround the segfault that occurs when used with fsevents"

package.json, scripts/build.js
There a known issues with `spawn` on Windows i.e. joyent/node#2318.
As a work around we sometimes use [cross-spawn](https://www.npmjs.com/package/cross-spawn). We will move all usage of `spawn` to `cross-spawn`.
Closes #1015.
=> Standardise on cross-spawn for spawning child processes

README.md, bin/node-sass
The multi-file terminology is unintuitive and could be seen as suggesting we support multiple input files, when in fact we're describing directory support.
Fixes https://github.com/sass/node-sass/issues/985
=> Update reference of 'multi-file' to 'directory'

.travis.yml
http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
=> Update to the new Travis CI infrastructure.

scripts/build.js
Make the build process output actually
useful.
=> Show actual compiler flags when building

appveyor.yml
This PR adds Node.js 4 support to AppVeyor matching the Travis config (https://github.com/sass/node-sass/pull/1130)
=> Add Node.js 4 to AppVeyor

binding.gyp, src/binding.cpp, src/callback_bridge.h, src/custom_function_bridge.cpp, src/sass_types/boolean.cpp, src/sass_types/color.cpp, src/sass_types/color.h, src/sass_types/error.cpp, src/sass_types/error.h, src/sass_types/factory.cpp, src/sass_types/list.cpp, src/sass_types/list.h, src/sass_types/map.cpp, src/sass_types/map.h, src/sass_types/number.cpp, src/sass_types/number.h, src/sass_types/sass_value_wrapper.h, src/sass_types/string.cpp, src/sass_types/string.h, test/api.js
We are running into trouble with C++ runtime
libraries (notably by mixing libstdc++ and libc++
on MacOSX). Reduce the risk by adhering to Google
Style Guide and stop using C++ exceptions at all.
libsass should offer us a pure C interface
and promises to not throw any exceptions as well.
While here, add additional checks for list and
map values.
Fixes: https://github.com/sass/node-sass/issues/1131
Closes: https://github.com/sass/node-sass/issues/1127
=> Do not use C++ exceptions in the binding code

.travis.yml
I've been following https://github.com/travis-ci/travis-ci/issues/2311 and it seems like getting a node project to build on OSX should be doable with some persistence.
~~I'm mostly just PR'ing this so Travis will build it. Feel free to ignore for the time being. This could be a complete failure.~~
It took a bit of doing but this works! I'm only building OSX for 0.12 and 4 for now to keep builds quicky-ish.
=> Run OSX builds in Travis CI

lib/extensions.js, test/runtime.js
Currently we show the unhelpful for `libsass` binding not found.
This accounts for a number of reoccurring GitHub issues. 
It's also the second largest driver of Google traffic to the node-sass GitHub repo.
```
Error: `libsass` bindings not found in /Users/michael/Projects/Sass/node-sass/vendor/darwin-x64-45/binding.node. Try reinstalling `node-sass`?
```
```
Error: The `libsass` binding was found in /Users/michael/Projects/Sass/node-sass/vendor/darwin-x64-45/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```
=> Provide a useful error message when the binding is not found

.gitignore, test/cli.js
Use two different directories for
directory watching CLI tests to
avoid races.
=> Avoid race conditon in watch dir tests

src/libsass.gyp
Windows delay hook feature is only needed
on the main module, linked into the shared
library. Don't compile and include
it second time in the bundled libsass.
Related: https://github.com/nodejs/node-gyp/issues/732
=> Don't compile delay hook into libsass

test/cli.js
Sometimes they generate double notification
on change:
1) cli node-sass in.scss should watch the full scss dep tree for a single file (scss):
Uncaught AssertionError: 'body{background:blue}\n\nbody{background:blue}' == 'body{background:blue}'
+ expected - actual
-body{background:blue}
-
body{background:blue}
at Socket.<anonymous> (test/cli.js:317:16)
at readableAddChunk (_stream_readable.js:146:16)
at Socket.Readable.push (_stream_readable.js:110:10)
at Pipe.onread (net.js:523:20)
https://github.com/sass/node-sass/issues/1152
=> Disable flakey dependency watching tests

appveyor.yml, package.json, src/binding.cpp, src/custom_function_bridge.h, src/custom_importer_bridge.h, src/libsass.gyp, src/sass_context_wrapper.h, src/sass_types/factory.h, src/sass_types/value.h
From now on, use includes from
src/libsass/include and the sources from
src/libsass/src
This is to be included when merging newer libsass.
=> Import libsass 3.3 code

README.md, lib/extensions.js, test/runtime.js
This PR adds the possibility to configure the sass-binary URL in the .npmrc configuration file (e.g.  `sass_cdnurl=http://example.com/sass-binaries`). This is also used the same way in [PhantomJS](https://github.com/Medium/phantomjs/blob/master/install.js#L23) by pointing the download URL to a mirror without having to set an environment variable manually.
=> Use sass binary url from .npmrc if available

README.md, bin/node-sass, test/cli.js, test/fixtures/follow/foo/bar/index.scss
Follow symlinked subdirectories when using --follow option. 
Note that this can result in a lot of duplicate references in the presence of cyclic links.
But it really helpful in a specific situations.
=> CLI: add --follow option

README.md
This pull request addresses issue https://github.com/sass/node-sass/issues/1204. Sass logo has been made a more appropriate size (77px - fits nicely with the adjacent npm image)
=> making sass logo size more appropriate

src/binding.cpp
node-sass 3.4 had a breaking public API change. This patch fixes the path that is passed as the previous file path when resolving imports. In node-sass 3.4 this value changed so that the import uri was passed. The issue here is that any code needed to resolve one import against another quickly falls apart if the resolved path returned by the importer is not what is passed back to the importer as the current sass file.
Basically, I think the updates for node-sass 3.4 to use libsass 3.3 mistakenly used the wrong value.
=> The previous file should be the absolute path, not the string used to import it.

test/api.js
Couldn't get the tests to run on my windows box:
> mocha test
fs.js:813
return binding.readdir(pathModule._makeLong(path));
^
Error: ENOENT: no such file or directory, scandir 'C:\Development\node-sass-test-case\node-sass\test\fixtures\spec\spec'
but running the new test in it's own file works for `v3.3.3` and fails for `v3.4.1`:
var sass = require('node-sass');
var assert = require('assert');
it('should still call the next importer with the resolved prev path when the previous importer returned both a file and contents property - issue #1219', function(done) {
sass.render({
data: '@import "a";',
importer: function(url, prev, done) {
if (url === 'a') {
done({
file: '/Users/me/sass/lib/a.scss',
contents: '@import "b"'
});
} else {
console.log(prev);
assert.equal(prev, …
=> Added a test for #1219

.travis.yml
The nvm version from master is unsupported and may be broken. Using a tag
is advised.
=> Use the last stable nvm, not the master version

README.md
Minor spacing error causing "file" to read as "f ile". Fixed.
=> Adjust incorrect spacing in README

test/cli.js
Until we can commit time to figuring out why they're failing randomly.
=> Disable randomly failing watcher tests

test/cli.js
This PR disables the final(?) flakey watcher tests until we have
time dig into the race condition causing failures. Having these
tests randomly failing builds is a terrible experience for
contributors.
=> Disable more flakey watcher tests

package.json
That latest version includes an update (mochajs/mocha@039a8a7) to a newer version (2.2.0) of `debug`, which in turn has updated (visionmedia/debug@adc2402) its dependency on `ms` to 0.7.1 in order to include a [security fix](https://nodesecurity.io/advisories/46).
Untested!
Ideally, please also do a point release including this fixed dependency.
=> Update mocha dependency to >= 2.3.4

test/api.js, test/cli.js
When the test fails, we are getting actual
values in the error message instead of
+ true
- false
=> assert(a === b) => assert.strictEqual(a, b)

lib/index.js, test/api.js
Whenever done() is called we should check for the sass.NULL
value as well.
While here, allow calling done(null) to anticipate
removal of the sass.NULL one day.
Closes https://github.com/sass/node-sass/pull/1308
Fixes https://github.com/sass/node-sass/issues/1296
=> Handle sass.NULL returned from the importer via done()

package.json
get-stdin wasn't bumped to ^5 because it introduced a breaking
change which would require use to drop support for node 0.10 or
add a promise library just for this module.
=> Bump npm deps

bin/node-sass, test/cli.js
Should fix the concern the user has in #1212 where using a symlinked output directory incorrectly errors out saying `An output directory must be specified when compiling a directory`
/cc @ysimonson
=> Allow symlinked output directories

lib/extensions.js, scripts/build.js
Remove red tape surrounding process.execPath
and use it as-is. In particular, do not try
to canonicalize the path returned by
process.execPath as this might be relative
in the restricted Linux environments
(for example using overlayfs).
We should be prepared to accept relative
or otherwise broken process.execPath and
have a faith it works (otherwise our
build scripts wouldn't be invoked
in the first place).
https://github.com/sass/node-sass/issues/1323
=> Accept process.execPath as-is

README.md
I just normalized the spelling of 'LibSass' for consistency purposes.
=> Normalize the way of writing 'LibSass' to the one used by the project

binding.gyp
=> Disables Thread-Safe for local static variables

appveyor.yml
This reverts commit 901f41149b79b173a7861b7871031dd2b52d8d3d.
=> Revert "Bump AppVeyor to use Visual Studio 2015"

appveyor.yml, binding.gyp
To ensure proper debugging of problems of Windows,
publish PDB debug file along with the binary.
In order to keep paths to the source files clean apply
the technique described by John Robbins in
"PDB Files: what every developer must know"
http://www.wintellect.com/devcenter/jrobbins/pdb-files-what-every-developer-must-know
and build node-sass in the "S:\node_modules\node-sass"
During debugging, source files can be referenced
via the virtual "S:" drive.
This allows users and developers to assign S: drive to the project
root ("node_modules") and access source files without having to redefine
source paths.
Artifact names are generated in a nice, Lisp-styled functional PowerShell
hidden in a YAML folded scalar!
Add node 5 to the PR testing build.
=> Publish debug file (PDB) of binding.node

package.json
LibSass 3.3.3 contained some massive refactoring. It pays to be cautions so we'll release a 3.5.0-beta first.
=> Release 3.5.0-beta.1

package.json, scripts/install.js
* Less dependency
* Use only stream
I use [got@5](https://github.com/sindresorhus/got/tree/v5.x) because node-sass support NodeJS 0.10 and 0.12.
/cc @sindresorhus 
Graph deps compare [Request Graph](http://npm.anvaka.com/#/view/2d/request) vs [Got Graph](http://npm.anvaka.com/#/view/2d/got)
=> Replace "request" by "got"

package.json
Maintainers get a lot of emails about errors from users whom we inevitably have to direct to the issue tracker.
I suspect this is because, when an error happens, users are encouraged to run either `npm bugs` or `npm owner ls`.
`npm bugs` would fail without a bugs url, so they'll move onto `npm owner ls` and subsequently email us.
By adding the `bugs` url to the package.json, _hopefully_ this will mitigate some of the emails the maintainers receive.
=> Add bugs url to package.json

test/api.js, test/fixtures/include-files/chained-imports-with-custom-importer.scss, test/fixtures/include-files/file-not-processed-by-loader.scss, test/fixtures/include-files/file-processed-by-loader.scss
I added a failing test case to demonstrate a bug in the current `importers`.
This error appears when you have custom `importers` defined, when a file has a chained import where the first import references a file not handled by the custom importer, and the second import is handled by the custom importer, the import order is broken.
=> Custom importers cause out of order chained imports.

.travis.yml, appveyor.yml
This PR does not mean we are dropping support for iojs. We're
simply not building it in CI. There are no new versions being
released for iojs and usage is [extremely low][0]. Since we're still
building iojs binaries for releases we don't risking breaking
support.
[0]: https://twitter.com/seldo/status/712386414902521861
=> Drop iojs from CI

package.json, scripts/prepublish.js
This is necessary because if a user is bundling node-sass in their
package, the vendor directory should stay so that the user isn't
required to run 'npm rebuild' afterwards, assuming that it was
originally installed on a like-architecture.
However, at the same time, when publishing, we don't want to include the
binaries since they may not work for a user plus there's the build step
that tries to download the correct binary for the current architecture.
Unfortunately, npm's prepublish hook runs on both prepublish *and* npm
install (see npm/npm#10074), so, using in-publish as a workaround to get
the prepublish script to only run prepublish and pack but not on
install.
Fixes #1183
Closes #1384
=> Remove vendor directory on prepublish and pack

lib/index.js, test/api.js
This allows custom functions to execute against the current render context. This is similar to the [current behavior of importers](https://github.com/sass/node-sass/blob/99dc18c448fcbb53b9e38d52eada3b39b3a57337/lib/index.js#L321).
This was discussed briefly in https://github.com/sass/node-sass/pull/783#discussion_r26910939
The benefit of this is that custom functions can persist data (be stateful), for the lifespan of the render.
This would allow you to do something like...
```js
{
...,
functions: {
"register-foo($foo)": function($foo) {
this.myNamespace.$foo = $foo;
...
},
"get-foo()": function() {
return this.myNamespace.$foo;
}
}
}
```
This would help alleviate some of the perf overhead we've seen with #1198. In our case, we currently store all stateful things in Sass variables and …
=> invoke custom functions with options.context

README.md
With #1291 custom importers can now return `null` instead of
`sass.NULL`. This means custom importer modules no longer need to
have node-sass as a dependency.
=> Update custom importer documentation to advocate returning `null`

bin/node-sass, lib/extensions.js, lib/index.js, scripts/build.js, scripts/install.js, test/cli.js, test/lowlevel.js, test/runtime.js
This replaces the global `process.sass` with proper module exports.
Unfortunately `process.sass`, although undocumented, is available
to other modules. This patch keeps the existing public API available
until we bump the major.
=> Remove use of global process.sass

lib/errors.js, lib/extensions.js, lib/index.js, test/api.js, test/errors.js, test/runtime.js
This is another iteration on improving the infamous
>The `libsass` binding was not found
Messages will now provide more useful information which will
- give users a chance to resolve the problem themselves
- give us more debug information from the error message alone
Error messages produced now be one of the following flavours:
>Node Sass does not yet support your current environment: OS X 64-bit with Node.js 4.x
>For more information on which environments are supported please see:
>http://....
****
>Error: Missing binding /tmp/node-sass/vendor/darwin-x64-47/binding.node
>Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 4.x
>
>Found bindings for the following environments:
>  - OS X 64-bit with io.js 3.x
>  - OS X 64-bit with Node.js 5.x
>
>This …
=> Better error messages for missing binaries

lib/index.js
This is an undocumented internal API that will be removed. Access
`process.sass` will produce the following warning.
>Deprecation warning: `process.sass` is an undocumented internal
that will be removed in future versions of Node Sass.
Continuation of #1427.
=> Ouptut a deprecation warning to stdout when using process.sass

lib/extensions.js, scripts/install.js
A regression introduced in 22c560c7 broke binary verification
causing the binary to always be built locally.
Fixes #1434
=> Fix a regression in binary verification

scripts/build.js
This is a messy first cut. We can revisit this in upcomming patches.
The value this will bring to debugging installation errors makes
this worth considered we're about to release a LibSass bump.
Fixes #1161
=> Log the error when there is a problem with the binary

lib/errors.js, test/errors.js
This would assume that a quick version table gets added to the release page after attaching the bindings during the release. EX:
OS | Node
------------ | -------------
Windows x86 & x64 | 0.10, 0.12, 1, 2, 3, 4, 5
OSX x64 | 0.10, 0.12, 1, 2, 3, 4, 5
Linux x86 & x64 | 0.10, 0.12, 1, 2, 3, 4, 5
=> Replace TODO URL with release tab for supported versions

lib/extensions.js, test/api.js
The human friendly name for an unknown platform, arch or runtime
is currently `false`. With this patch the user is better informed
as to why their environment is unsupported. The raw value is also
output to ease with bug reports.
Closes #1487
=> Improve error message for unsupported environments

src/callback_bridge.h, src/sass_types/boolean.cpp
This was partially addressed by bumping NAN in #1496.
https://github.com/nodejs/node/issues/6216
https://codereview.chromium.org/1839983002/patch/1/10002
Fixes #1484
=> Fix final Node 6 deprecation warnings

.travis.yml
Previous we manually installed NVM and did the version switching
ourselves. This was required because Travis didn't support NVM
on OSX builds. This has since [been fixed][1] so lets see how it
goes.
[1]: https://github.com/travis-ci/travis-ci/issues/2311
=> Simplify Node versions in Travis Ci

appveyor.yml
Node 6.x has trouble probably including
modules from the substed drivers.
Since we use use subst only to set
symbols paths in the PDB file, let's
revert to the C: drive when doing tests.
Workaround for: https://github.com/nodejs/node/issues/6500
=> Node 6 for Windows: Don't use subst for testing

appveyor.yml
Currently it's a bit of an ordeal trying to get the atomic puush
required for AppVeyor to register a commit on the release branch
and also a tag. Looks like AppVeyor expects you to do release from
the master branch.
Inspired by @nschonni work in #1518 in an attempt to work around
this issue this PR instructs AppVeyor to ignore tags on non-release
branches.
Fingers crossed this makes like easier.
Closes #1518
=> Attempt to fix AppVeyor tag race condition

lib/extensions.js
Renamed parameters to be a little clearer, and marked them public since
they are being exported
=> Docs: Add jsdocs for human readable public methods

bin/node-sass
Currently we build the Sass import graph when the CLI watcher is
started. However the graph is not update updated when files are
added or deleted. The latest is a big deal but the former results
in new files not triggered rebuilds when they're changed. The only
way to currently resolve this is to restart the CLI watcher.
This patch rebuilds the Sass import graph when files are added or
deleted to the watch always works as expected.
Fixes #1538
=> Update watched file list when files are added or removed

scripts/build.js
Fixes: https://github.com/sass/node-sass/pull/1631
Fixes: https://github.com/electron/electron/issues/6462
Broken-By: https://github.com/sass/node-sass/pull/1101
Fix-Provided-By: https://github.com/sass/node-sass/pull/1631
=> process.config may be empty (electron)

.travis.yml, package.json
This allows us to bump beyond ESLint 2.x in the future since it dropped support for Node <4
=> Build: Rename pretest to lint and only run once in CI

ISSUE_TEMPLATE.md
Taking a kick at https://help.github.com/articles/creating-an-issue-template-for-your-repository/
It might make sense to merge some of the Troubleshooting/Contributing content directly here later.
The "supported platforms" I linked to is out of date and may not be useful as-is.
PS: This could also get moved to a `.github` folder in the root to keep it cleaner.
=> Add an Issue template to help triage the backlog

binding.gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.5 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Justin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Justin\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Justin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Justin\\.node-gyp\\4.4.5\\include\\node\\common.gypi',
gyp info spawn …
=> libsass_ext is not defined

lib/index.js, test/api.js, test/fixtures/sass-path/expected-orange.css, test/fixtures/sass-path/expected-red.css, test/fixtures/sass-path/index.scss, test/fixtures/sass-path/orange/colors.scss, test/fixtures/sass-path/red/colors.scss
This is intended to [implement the `SASS_PATH` environment variable](https://github.com/sass/libsass/issues/90#issuecomment-57822790).
Fixes #1678.
I've added two new API tests under `.render`:
- "should check SASS_PATH in the specified order"
- "should prefer include path over SASS_PATH"
If you run `mocha test/api.js` you should see these tests pass.
You can test it manually using the test fixtures as follows:
``` bash
$ fixdir=`pwd`/test/fixtures/sass-path
$ export SASS_PATH=$fixdir/red
$ bin/node-sass $fixdir/index.scss
body {
background: red; }
```
``` bash
$ export SASS_PATH=$fixdir/orange:$fixdir/red
$ bin/node-sass $fixdir/index.scss
body {
background: orange; }
```
``` bash
$ bin/node-sass $fixdir/index.scss --include-path $fixdir/red
body {
background: red; }
```
=> Implement SASS_PATH

scripts/install.js
This PR adds a 1s timeout to the binary fetch request as well as a
useful error message.
It came to light in #1690 that the download can block for a long time.
```
npm info lifecycle node-sass@3.8.0~install: node-sass@3.8.0
> node-sass@3.8.0 install /Usersproject-path/node_modules/node-sass
> node scripts/install.js
Build timed out (after 35 minutes). Marking the build as failed.
```
We see a fair amount of hung installer issues that could be related
to this. The error output will give us another data point in those
cases.
=> Add a timeout to the binary fetch request

test/cli.js
For some reason our test fail due to timeouts on seemingly random
cli tests. This instability has been growing worse. I've spent the
better part of the last two days looking into the issue without a
resolution. I'm starting to think it's an artefact cause by the
virtualisation used in CI, potentially related to resources
starvation.
The specs that failure do so trying to spawn a child process. The
process never spawns resulting in an eventual timeout. This is why
@nschonni attempt addressing this by increasing the timeout in #1668
failed.
Since the spawn failure is random, and catastrophic the best solution
in the short-medium term is to instruct mocha to retry failing tests
individually a couple times.
I've scoped this behaviour to the cli specs because at the moment
we have some specs …
=> Retry CLI specs that fail three times

scripts/install.js
The timeout applies to both the initial connection as well as
individual packets.
I found the 1s timeout to be really fragile when testing locally.
The intent of the timeout is to prevent the install process hanging
indefinitely. It makes sense to be very generous so this increases
the timeout to 60s.
=> Increase the binary fetch request timeout

package.json, scripts/install.js
Forked from #1649.
This PR adds a small ascii progress bar to the binary download.
Stalled installations make up a steady background noise of our
issues. It's my hope that by making the binary fetch more
transparent we can stem the tide of those issues.
In order to address @saper's [concerns][1] this progress bar will
respect npm's `progress` config flag.
Closes #1649
[1]: https://github.com/sass/node-sass/pull/1649#issuecomment-242720257
=> Add a nice little progress bar while downloading binary

package.json
This is required for nodejs/citgm#165.
I conceed it will increase the size of the tarball. This isn't ideal
given the background noise of installation issues atm, but IMHO the
value of being in the CITGM is worth it.
The additional transparency into the binary download added by #1649
will go a long to alleviating the addition tarball size.
=> Publish tests to npm

README.md
Also, added the `or` word to clarify the two lines are not to be run sequentially.
=> Move the two CLI Usage into separate lines

appveyor.yml
This slows down the release builds and in the worst case scenario
causes a single job failing meaning we need to rerun the entire build.
Problems with tests will have been caught we'll before we start
building release binaries.
Thoughts @saper?
=> Don't run tests when building a Windows release

test/cli.js
This test is super flakey for some reason, and `before` hooks also
appear to be get retried by mocha.
The was only required for when testing against LibSass < 3.3 which
is no longer the case. As such this hook serves no purpose.
=> Remove the cli before test

package.json
Reverts sass/node-sass#1688
This has caused multiple issues. We still need this but we need to rethink our approach.
Fixes #1701
Fixes #1699
Fixes dlmanning/gulp-sass#529
=> Revert "Publish tests to npm"

.eslintrc.json, .jshintignore, .travis.yml, bin/node-sass, package.json, test/api.js
- Bump to the 3.x branch since we only run it in Node 4
- Add the recommended options, but left our existing overrides
- Rename the eslintrc file to JSON to match the newer format that allows it to skip guessing
- Delete the old jshintignores since it is no longer applicable
- Enforce and fix a few variable declaration issues
- Ensure the lint runs during the regular Travis script section so it fails the build
=> ESLint 3.x updates

lib/index.js, package.json
This was never part of the public API, and has officially been depreciated in Node 6 https://github.com/nodejs/node/pull/4903
=> Replace util._extend with Object.assign

scripts/install.js, scripts/util/useragent.js, test/useragent.js
The installer is getting more complicated. The core of it is a http
request which makes testing it difficult/messy. Pulling out core
logic into small util functions that we can unit test would give me
much more confidence moving forward.
I would prefer we don't export functions from scripts so people don't
start relying on undocumented APIs. This is why I opted for helper
utils but I'm not committed to them.
@nschonni this is along the lines of what I was thinking in our Slack
chat today. I've applied it the same approach in #1725 as an example.
Would love to hear your thoughts.
=> POC for adding unit test coverage to install

lib/extensions.js, scripts/install.js, test/runtime.js
New order of operations
1. Look for existing binary in vendor folder
2. Create target vendor folder
3. Look to see if we’ve cached a copy in the configured or NPM cache
4. Download to current version’s /CACHE/node-sass/version/binding_file
5. Copy the cached download to the regular vendor directory
Closes #1566
=> User configurable cache folder for binary download

package.json, scripts/install.js, scripts/util/proxy.js, test/scripts/util/proxy.js
Turns our handling proxies is complicated. The sanest thing to do
is try matching [npm's behaviour](https://github.com/npm/npm/commit/40afd6aaf34), and liable [to change](https://github.com/npm/npm/commit/40afd6aaf34) to
our benefit. The TLDR; of which is to let `request` do whatever
it wants unless npm has been explicitly configured otherwise.
Fixes #1724
/cc @nschonni @mmrath
=> Respect NO_PROXY when downloading the binary

scripts/install.js, scripts/util/downloadoptions.js, test/downloadoptions.js
In #1725 we started setting `proxy: ''` to defer proxy resolution
logic to request. However `request` uses `hasOwnProperty` rather
than falsey checks to determine if an option has been set. This
caused `request` to believe were configuring a proxy so it didn't
do it's own proxy resolution.
Fixes #1785
Fixes #1787
=> Fix proxy config for binary download

scripts/install.js
npmlog has the advantage of using the same log level configuration of npm.
Running `npm install gulp-sass --no-progress --silent` I found out that this package is particularly noisy.
=> Switch from console.log to npmlog

bin/node-sass
=> Add descendent files to watched files

lib/extensions.js, scripts/build.js, scripts/install.js
In for a penny in for a pound. I also  noticed that #1786 resulted
in some funky looking console output. I've taken this opportunity to
tidy up our install script output whilst maintaining the information
useful for debugging install issues.
```
> node-sass@3.11.3 install /Users/xzyfer/Projects/Sass/upstream/node-sass
> node scripts/install.js
http node-sass install Downloading binary from https://github.com/sass/node-sass/releases/download/v3.11.3/darwin-x64-47_binding.node
http node-sass install Download complete
info node-sass install Binary saved at /Users/xzyfer/Projects/Sass/upstream/node-sass/vendor/darwin-x64-47/binding.node
> node-sass@3.11.3 postinstall /Users/xzyfer/Projects/Sass/upstream/node-sass
> node scripts/build.js
info node-sass build Binary found at …
```
=> Use npmlog for all install script output

lib/extensions.js, scripts/install.js, test/runtime.js
This uses a candidate model for determining an suitable cache
directory. This is different from the current approach with eagerly
chooses a cache directory. If that directory isn't accessible for
some reason (i.e. permissions) we have to bail out. With this
approach we can try a prioritised list of candidate directories.
Additionally this address the case where npm cache config is
blank.
Fixes #1781
=> Handle permission errors when attempting to cache binaries

scripts/build.js, scripts/install.js
We started using npmlog for install logging in #1786, then went all
out in #1796. npmlog has caused some issues, namely #1805. It doesn't
provided enough value for how troublesome it is.
The problem sparked #1786 was resolved in 5c7fb7f675.
=> Use console for logging instead of npmlog

README.md
expand on sourceComments description in README.md
=> update sourceComments documentation in README.md

lib/index.js
This helps fix the case when passing in a string instead of object for options (when used programmatically).
Fix #1824.
=> Check options to be an object

bin/node-sass
Looking at [the commit that introduced it,](https://github.com/sass/node-sass/commit/c7539f19d2e97cd52cf7a52c00c8e8fff3f4409a) it seems that it's leftover of the `cli.js` which was then required in a separate file.
Closes #1826
=> Removed top-level return statement from cli

package.json, test/spec.js
Fixes #1829.
The code of `lodash.isarray` is actually this:
```js
var isArray = Array.isArray;
module.exports = isArray;
```
=> Drop dependency lodash.isarray

lib/extensions.js, package.json
This adds a new element `platformvariant` to the naming scheme for precompiled binding binaries:
```
{platform}_{platformvariant}-{arch}-{abiversion}_binding
```
This allows for statically compiled musl binaries to be made available for Alpine Linux.
The check for whether this is needed is done by detecting symbols in the node binary, as suggested in https://github.com/sass/node-sass/issues/1589#issuecomment-266470069. I don't love this approach, but it's a whole lot simpler than `exec`'ing out to `ldd`. 
See https://github.com/sass/node-sass/issues/1589 for more details on background.
Tests:
```bash 
$ docker run -v "$PWD:/code" --rm -w /code node:7-alpine node scripts/install.js 
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.0.0/linux_musl-x64-51_binding. …
```
=> Add a platform variant for installing a musl binary

CONTRIBUTING.md, README.md
As of #1850 we no long have a LibSass git submodule.
=> Remove git sub module documentation

scripts/build.js
The git submodule is removed as of #1850.
This was added by me in #874 to support node-sass being installed
as a gitish via GitHub rather than the npm registry. 
We publish the LibSass src to npm already so it should continue
to work as is.
=> Remove the git fallback

appveyor.yml
Node change to Visual Studio 2015 when Node 6 went to LTS.
See nodejs/node#7989
Fixes #1854
=> Use Visual Studio 2015 for Node 6+

bin/node-sass
Watching for changes on files with lots of `@import`s had a
significant regression in responsiveness in #1745.
The regression was caused by calling `gaze.add` unnecessarily. We
only need to call `gaze.add` on files that aren't currently being
watched.
At the time I confirmed that calling `gaze.add` in files that were
being watched wouldn't result in a leak or multiple events being
fired. I however assumed calling `gaze.add` for already watched
files would be very cheap.
Fixes #1869
=> Make the watcher more responsive to child changes

appveyor.yml
The AppVeyor config was updated in #1870 but I missed some changes
for the release config.
=> Update AppVeyor release config

lib/index.js, test/api.js, test/fixtures/cwd-include-path/expected.css, test/fixtures/cwd-include-path/outside.scss, test/fixtures/cwd-include-path/root/index.scss
Traditionally Sass has added the cwd as the first include path. This
behaviour was remove in Sass 3.4, and recently in LibSass 3.5.0.beta.2.
People depend on this behaviour and as a result a lot of compilations
are now failing.
This PR restores the expected behaviour and adds a test to boot.
Fixes #1876
=> Restore behaviour of cwd in include path

lib/errors.js, scripts/build.js
Running `npm rebuild node-sass` as we instruct people, has been
noop for a while. I'm not entirely sure what has changed.
Debugging has revealed that running `rebuild` now just triggers the
`install` and `postinstall` scripts. The `build` script is no
longer run. This suggests something has changed in newer versions
of npm.
Since the `--force` flag is required to rebuild the binary I've
update the `build` script to take into account if `--force` was
passed to npm.
=> Fix npm rebuild

package.json
_request 2.78.0 uses deprecated node-uuid, it has been updated in version 2.79.0 to use uuid package, an unwanted warn is shown in the console when npm installing node-sass_
_bump request dependency version to 2.79.0_
=> Update request version to avoid npm warn

README.md
I've updated the link to Visual Studio 2013 WD so that it is accurate. The old link now points to a more recent version.
=> Update Link: Create a link to correct VS

lib/extensions.js, test/binding.js
This is a workaround for nodejs/citgm#389. The install/build flow
needs to be updated so that unsupported environments result in an
informative warning instead of a failure.
=> Add Node 8 to the support versions lists

lib/extensions.js
V8 5.7 landed recently in node core, causing the module version to get bumped.
=> Update module version for node v8.x

lib/extensions.js
Was 54 is now 55 will soon be 57.
=> Update module version for Node 8

.travis.yml
This is still beta, but I thought I'd give it a try.
Instead of running the full matrix at once, run the mainline node release linting and coverage, and then run the rest if that is ok.
I think in the end there could probably be a "docker" phase to maybe run some alpine stuff in the future. It could also be used to orchistrate the releases, although there would need to be some sync/handshake with AppVeyor
=> Build: Use Travis Stages

lib/extensions.js
This adds the respective Electron ABI versions to `getHumanNodeVersion()`
to enable running `node-sass` under Electron where the ABI versions differ from Node's.
=> Add Electron ABI versions

bin/node-sass, lib/watcher.js, package.json, test/fixtures/watcher/main/one.scss, test/fixtures/watcher/main/partials/_one.scss, test/fixtures/watcher/main/partials/_three.scss, test/fixtures/watcher/main/partials/_two.scss, test/fixtures/watcher/main/two.scss, test/fixtures/watcher/sibling/partials/_three.scss, test/fixtures/watcher/sibling/three.scss, test/watcher.js
This logic is all tightly coupled in the bin. This logic has been
notoriously impossible to test due to weird fs timing issues. By
extracting the actual logic we're now able to test it in isolation.
With this in place replacing Gaze (#636) becomes a viable option.
This PR not only massively increases our test coverage for the
watcher but also address a bunch of known edge cases i.e. orphaned
imports when a files is deleted.
Closes #1896
Fixes #1891
=> Decouple the graph and render logic from the fs watcher

.travis.yml, README.md, appveyor.yml
These will always fails now due to https://github.com/sass/node-sass/issues/2100. We manually verify support when building release binaries so there's no value in failing CI. It's scary to contributors.
=> Remove Node 0.10 and 0.12 from CI config

.travis.yml, appveyor.yml, lib/extensions.js
Related to #2129, but not sure NVM has the tags yet for `carbon`
=> Node 9 support

README.md
Pointing them to the release notes is safer since it will accurately reflect the support for that version of node-sass
=> docs: Update the Node version support message

bin/node-sass
Since it returns an object, we need to run through the keys, a simple index of isn't enough.  This should fix https://github.com/sass/node-sass/issues/2139
=> gaze.watched returns an object

memory-tests/_measure.js, memory-tests/boolean.js, memory-tests/function-bridge.js, memory-tests/map.js, memory-tests/string.js, src/binding.cpp, src/callback_bridge.h, src/custom_function_bridge.cpp, src/custom_importer_bridge.cpp, src/sass_types/boolean.cpp, src/sass_types/boolean.h, src/sass_types/color.cpp, src/sass_types/factory.cpp, src/sass_types/list.cpp, src/sass_types/map.cpp, src/sass_types/null.cpp, src/sass_types/number.cpp, src/sass_types/sass_value_wrapper.h, src/sass_types/string.cpp, src/sass_types/value.h, test/api.js, test/types.js
[FIXES #2098]
We noticed our ember-cli builds for linkedin.com were consuming ~10gb of memory, [after some investigation](https://github.com/sass/node-sass/issues/2098) node-sass (via eyeglass) was identified as the primary culprit. With this PR, memory usage dropped by from ~10gb -> ~1gb (saving about 9gb of ram)
**NOTE: This does not fix all the leaks, more PR's to come**
* `create_string` must be paired with a free (this catches a few of the easy ones)
* number constructor's unit (`sass_make_number` copies the unit)
* string constructor's value (`sass_make_string` also copies the string)
* Bindings `ExtractOptions` function signature (`sass_make_function` copies the `signature`)
* `SassTypes::Value` are now subclasses of `Nan::ObjectWrap`, and we utilize its machinery for memory …
=> Fix Some Leaks

.github/ISSUE_TEMPLATE.md
Although some might ignore our issue template, this might head off some issues of people running unsupported node-sass/Node versions
=> Add checking release page to the ISSUE_TEMPLATE

appveyor.yml
We still want these till we officially drop the EOL Node versions.
Closes #2222 
I did a hacky Appveyor build to generate the release binaries here https://ci.appveyor.com/project/nschonni/node-sass/build/97
=> build: Add back Appveyor 0.12-3

.github/ISSUE_TEMPLATE.md
Saw this trick in another repo and though it made sense
=> Use HTML comments to show a reduced Markdown in Contributing.md

bin/node-sass
- Emit normal output as info not warn
- Don't emit info output in quiet mode
=> Respect quiet option in Node API

package.json
I ran into [an issue][1] compiling the iojs 3 binary on OSX. This
sound affect anyone in reality but just in case.
[1]: https://github.com/nodejs/nan/pull/728
=> Bump minimum nan@2.9.2

lib/extensions.js
Lets try to avoid the rush of issues when Node 10 is released next
month.
Node 10 is currently version [`62`][1] but is expected to be
[`63`][2] before going stable. We need to pick one because of the
ABI breakage between 62 and 63.
If this bet pays off we save ourselves a bunch of time dealing with
installation issues, and avoiding a new release. If we're wrong it's
no different to any other major Node release.
[1]: https://github.com/nodejs/node/blob/97595739/src/node_version.h#L112
[2]: https://github.com/nodejs/node/pull/19201
=> Pre-empt support for Node 10

bin/node-sass
Updated the node-sass cli script to use the watcher removed function instead of the 'deleted' function which is non-existent.
Fixes #2248
=> Use watcher removed function on deleted

README.md, lib/extensions.js, test/runtime.js
I'm at a company with people developing on multiple platforms behind a strict firewall. I want to host precompiled SASS bindings locally so setting SASS_BINARY_URL doesn't work for me. However I do not want to use SASS_BINARY_PATH because it requires giving explicit file name of the binding which doesn't work when some developers are on Macs, some on WIndows, and the whole project is compiled on Linux for production — it is quite a pain to set the full path as required in each environment, and as far as I know impossible within a static .npmrc file (.npmrc supports expansion of environment variables but I'd still need to set the SASS version, OS arch & Node Modules version).
Introducing: SASS_BINARY_DIR! Enables setting a directory where the binaries are stored but uses the default file …
=> Allow setting of SASS_BINARY_DIR without setting explicit binary name

scripts/install.js
Currently the binary download is streamed to disk once a 200 response
has been recieved. When an error occurs during the download a partially
downloaded binary is left on disk. Subsequent installs see the binary
and bail out of re-downloading it. Worse yet those subsequent installs
move the binary into the global cache so even removing node_modules
will not remove the broken binary.
With this patch the binary is only flushed to disk once it has been
fully downloaded.
Fixes #1882
Fixes #1888
=> Install script should not write partially downloaded binaries

scripts/install.js, scripts/util/downloadoptions.js, test/downloadoptions.js
Due to #1912 we were writing binaries to disk with the encoding.
We need to do some additional juggling when dealing with binary
data.
=> Fix wrong binary encoding

package.json, src/libsass/docs/implementations.md, src/libsass/src/check_nesting.cpp, src/libsass/src/context.cpp, src/libsass/src/eval.cpp, src/libsass/src/functions.cpp
=> Bum LibSass to 3.5.1

lib/extensions.js
=> [v5] Remove workarounds for old Node.js versions

package.json
I based the range on what's indicated in `.travis.yml` but since Travis always defaults to the newest release in each series a higher minor could be selected as well.
Especially Node.js 4.5 might be a good pick since it's the first release to support `Buffer.from`, `Buffer.alloc` and `Buffer.allocUnsafe`.
In #2111 I found this mention in the summary:
> Moving forward we'll only be actively supporting active LTS and current Node versions. In practical terms this means Node 6+.
But it's not currently reflected in the Travis config.
Relates to #2312
=> [v5] Indicate the supported Node.js version in package.json

src/binding.cpp, src/callback_bridge.h, src/sass_context_wrapper.cpp, src/sass_context_wrapper.h
EDIT: This is an improvement on some of the fixes in #2295.
Starting with Nan 2.9.0, we have the ability to propagate async context
across async hops. Certain variants of Nan::Callback::Call are now
deprecated to encourage use of the context presevering alternatives.
Certain variants of Node's MakeCallback that were used internally are
going to be deprecated in Node 10.
Summary is that one should use Nan::Call for sync calls, and
Nan::Callback::Call for async. The latter expects an async resource
corresponding to the async operation to be provided at the call time.
This patch fixes things up so that 1) node-sass isn't using any
deprecated APIs, and 2) properly propagates async context for async
callbacks by creating async resources in the appropriate places.
Related: …
=> fix: propagate async context

lib/extensions.js
#2274 tried preempt Node 10 module version, but missed the mark.
Node 10 is now in RC as `64`. I've confirmed Node Sass compiles and runs with OSX.
=> Fix Node 10 check

package.json, src/libsass/src/sass2scss.cpp
Bump LibSass@3.5.4 to address some regressions in LibSass@3.5.3.
https://github.com/sass/libsass/releases/tag/3.5.4
Lock to sass-spec@3.5.4-1 because of specs that depend on features
reverted in 3.5.4.
=> Bump LibSass@3.5.4

README.md
solves #2370 
with relative path to troubleshoot guide, npm was unable to direct to correct page. Now its corrected using absolute path.
=> Updated links to absolute path instead of relative

bin/node-sass
It is not clear from the `--help` docs that `--source-map` requires a boolean or path. Passing the flag alone results in a TypeError. There's an argument to be made that passing the flag alone should imply `true`, or at the very least it should fail with a helpful error, not a cryptic TypeError. For now, this PR fixes the --help docs so that they match the README.
=> docs: Clarify --source-map flag. Closes #1026.

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Compile_results_are_incorrect.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/ISSUE_TEMPLATE/Installation_Problem.md, .github/ISSUE_TEMPLATE/Request_Security.md
Related to https://github.com/sass/node-sass/issues/2365 but we'll need to actually setup the templates themselves before that one can be closed
=> Split issue templates

TROUBLESHOOTING.md
Add a separate section in the TROUBLESHOOTING about the 404 downloads. Not sure if the wording is the best, but I think we should add some section like this
=> docs: add more 404 binding install info

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, appveyor.yml, package.json
request@2.87.0 removed the dependency on `hoek` (request/request#2943)
which restores support for Node < 4. This means we bump to the latest
`request` to resolve the `npm audit` warnings.
Additionally I had to bump `coveralls@^3` to resolve a dependency
mismatch with `request`.
I've added back the CI checks for old Node for the v4 branch.
Fixes #2355
=> Bump request@2.87.0 

.travis.yml
Not sure if anyone is still using the channel, but the CI messages probably aren't useful there anyway
=> chore: Remove Travis Gitter hook

package.json
The package `extend 3.0.1`, which is a dependency of `request 2.87` has a vulnerability :
https://hackerone.com/reports/381185
Upgrade `request` to v.2.88 will install `extend` v.3.0.2, the fixed version.
Fix #2496
=> Upgrade request package to v.2.88

.travis.yml, appveyor.yml, lib/extensions.js
=> Add Node 11 support

README.md
Hi all! 👋 As I don't have access to my old GitHub account anymore (I lost the 2FA backup code to the `adamyeats` account years ago and can't log in), and no longer have access to the `sass` organisation, I am removing myself from the maintainers list.
Best wishes to all and good luck! 👍
=> Remove @adamyeats from maintainers list

.travis.yml
'sudo' seems to be unavailable.
Remove sudo settings from .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> Remove sudo settings from .travis.yml

README.md
The archive link was supposed to go to a GitHub Wiki page, but that was nonexistent; I replaced the link to the official instructions from [nodesource/distributions](https://github.com/nodesource/distributions).
=> Fix broken link to NodeJS docs in README.md

.travis.yml
Node 12 is built using GCC 6 therefore
it is mandatory that we use the same C++
runtime as the mothership.
=> Use GCC 6 for Node 12 binaries

README.md, lib/index.js, test/api.js
render() and renderSync() should return "map" property in the results
only if source map has been enabled.
=> Fix #2394: sourceMap option should have consistent behaviour

.travis.yml, appveyor.yml, scripts/install.js
This flag means we skip a bunch of code paths in CI which is not
ideal. Since we tell people to use `npm rebuild` we should eat our
own dog food.
With this patch we do an install, then do a rebuild hitting all the
major install code paths.
Fixes #1453
/cc @nschonni @saper
=> Remove skip download for CI flag

.travis.yml, lib/extensions.js, package.json
Follow-up to #2647, but instead of using a new CI service we use [Travis new support for multiple CPU architectures](https://docs.travis-ci.com/user/multi-cpu-architectures/)
=> Test against arm64 on Travis

package.json
chalk v3 drops support for node < 8 and brings performance improvements
=> chore: update chalk to v3

.travis.yml, README.md, appveyor.yml, lib/extensions.js
=> feat: Add Node 14 support

package.json
@xzyfer can we push 4.13.0 to include this? unfortunately the binaries have to be re-built
Fixes #2621
=> Fix #2621: Report libsass version 3.5.5

.github/workflows/alpine.yml
Adds some CI for the Alpine images to speed up releases.
If this works out, I might take a look at converting some of the others.
This also uploads the artifacts as a zip on successful builds. This could be modified to only run on tags later
Note: ran into an issue with the Node 8.17.0 alpine images. You can see an example log here https://gist.github.com/nschonni/491cd2ae724e1f24db3b76b37698ab1c
Main issues is probably around
```
2020-01-18T03:50:16.3975372Z npm ERR! Command failed: git clone --mirror -q https://github.com/sass/sass-spec.git /github/home/.npm/_cacache/tmp/git-clone-dbd532b1/.git
2020-01-18T03:50:16.3975793Z npm ERR! /github/home/.npm/_cacache/tmp/git-clone-dbd532b1/.git: Permission denied
```
where the git sass-spec is failing. Tried a bunch of troubleshooting, but just …
=> chore: Add GitHub Actions for Alpine CI

package.json
This release fixes #2912 without breaking BC. See https://github.com/xzyfer/sass-graph/pull/110
=> Bump sass-graph@2.2.5

bin/node-sass
CodeQL was flagging the second `else if`.
Looked at code and inlined the single use so it's not executed if
first condition is true.
=> fix: Flatten sourceMap folder detection

.github/workflows/coverage.yml
Fixes the Coveralls upload by using their GitHub Action.
Could probably refactor this, and might be able to go away later with the istambul -> nyc change
=> chore: Add GitHub Coveralls

package.json
Bumping Mocha uncovered a minor issue with the tests not cleanly exiting for the watch on Windows, but updated cross-spawn seems to resolve that again
=> chore: Bump cross-spawn to v7.0.3

README.md, package.json
- Add an attempt at a support policy for Node versions at the top of the readme. I removed the old heading text, so some old links might break
- Replaced the Travis status badges with the new GitHub Actions ones
- Removed old status badges for services we don't really rely on
@xzyfer should the Slack on be removed as well? I don't know if it gets much attention by anyone
=> chore: Prep README for v5

lib/extensions.js
=> Remove workarounds for old Node.js versions

.github/workflows/alpine.yml, .github/workflows/coverage.yml, .github/workflows/lint-js.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
These are submitted by PR, so branches don't need to build
=> chore: Don't double build DependaBot PRs

.github/workflows/alpine.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, README.md, appveyor.yml, lib/extensions.js, package.json
This should fail till the actual v15 of Node comes out.
Platform compiler requirements based off of https://github.com/nodejs/build/issues/2423
=> chore: Add Node 15 support

.github/workflows/alpine.yml
Matching the current defaults from https://github.com/nodejs/docker-node/blob/main/versions.json
A bunch of the current defaults are EOL versions of Alpine, so the tags are out of date
=> chore: Use default Apline version from docker-node

README.md, scripts/util/downloadoptions.js, scripts/util/rejectUnauthorized.js, test/downloadoptions.js
Resolve CVE-2020-240-25 by setting rejectUnauthorized to true by default.
Add configuration flag to override this to false if necessary.
Add doc option to README.md
=> Set rejectUnauthorized to true by default

.github/workflows/alpine.yml
New node-gyp no longer supports Python 2
=> ci: use Python 3 for Node 12

.github/workflows/alpine.yml
Inlined the python 3 since that is the only version used now.
This should be looked at, but it's easier to miss actual breakages when the CI is perma-red right now
=> chore: disable Apline for Node 16/17 builds

.github/workflows/alpine.yml, package.json, scripts/install.js, scripts/util/downloadoptions.js, test/downloadoptions.js
cf: https://github.com/sass/node-sass/issues/2851
Follows the implementation that was done here: https://github.com/sass/node-sass/pull/2961 ; also remove `npmlog` that seems unused from here on.
Because the latest node-gyp does not support python2 (https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#810-2021-05-28), use python3 for all nodes builds/tests. (Not sure if `src/libsass/script/ci-report-coverage:8` should be affected?)
=> Use make-fetch-happen instead of request

.github/workflows/windows.yml
=> chore: bump GitHub Actions to Windows 2019

README.md
This repo was moved to the docpad org
=> docs(readme): fix docpad plugin link

scripts/install.js
I think this fixes master and unblocks new releases.
Regressed in #3193
Fixes #3300
=> Fix binaries being partially downloaded

package.json
Fixed failing binary compilations on Node 19.
=> Bump node-gyp and nan for node 19 support
