- README.md
> Added hint for rebuilding

- src/binding.cpp
> Code: Don't push to vector for Render*Sync

- bin/node-sass
This PR stops the process exiting on successful compilation your watching a file or directory.
> Dont exit on successful compilation if watching

- bin/node-sass
- test/cli.js
Attempts to address #621.
Also added a test.
> CLI: Simplifies path resolution for dest

- package.json
> Pakcages: Updated all to latest versions

- package.json
* Updates packages to latest versions.
* Addresses issue described here: https://github.com/sass/node-sass/issues/627#issuecomment-73322407.
> Package: Adds pangyp to devDependencies

- package.json
* Locking down v2.0.0.
Related Issue: #602.
> Package: Updates libsass verion

- lib/extensions.js
- scripts/install.js
> Code: Minor fixes.

- README.md
- bin/node-sass
- lib/index.js
- lib/render.js
- src/binding.cpp
- test/api.js
- test/cli.js
- test/fixtures/image-path/expected.css
- test/fixtures/image-path/index.scss
Issue URL: #702.
Also removed the obsolete underscore-separated options names.
//cc @xzyfer
> API: Retires non-standard image-path option.

- .npmignore
- package.json
Based on https://github.com/sass/node-sass/commit/fffc06259cc383f14218bb159b7bdbd6ce95d932#commitcomment-8369073.
> Repo: Removes .npmignore, configures package.json

- package.json
* Also moves cross-spawn under `devDependencies`.
> Package: Removes unused pacakge 'object-assign'

- lib/index.js
- src/binding.cpp
* Removes unnecessary delete statements. 
* Moves cb related options in render.
> Code: Improvements

- lib/index.js
> API: Resolve input, output and map w.r.t. cwd

- scripts/install.js
> Install: Fixes download bug :bug:

- lib/extensions.js
> Code: Minor formatting

- .gitattributes
Issue URL: #758.
//cc @mgreter
> Repo: Adds .gitattributes

- lib/extensions.js
- test/api.js
> Code: Parses arguments manually

- lib/render.js
- package.json
- scripts/build.js
- src/create_string.cpp
- src/custom_function_bridge.cpp
- src/custom_importer_bridge.cpp
- src/sass_types/boolean.cpp
- src/sass_types/color.cpp
- src/sass_types/factory.cpp
- src/sass_types/map.cpp
- src/sass_types/null.cpp
Because `.editorconfig` say so..
> Code: Mics. formattings

- lib/extensions.js
- scripts/build.js
> Code: Improves binary test

- .editorconfig
- README.md
`<span/><span/>` to more `<p/><p/>`
> ad br so readme cli options differentiate

- README.md
- src/custom_importer_bridge.cpp
- src/custom_importer_bridge.h
- test/api.js
> Importer: Throws error on invalid return type

- src/callback_bridge.h
It is not safe to delete uv_async_t object after
calling uv_close(). This object remains in the
closing queue and can be purged only in the final
callback.
> Close #713 (handle->flags & UV_CLOSING) assertion failure

- README.md
This PR updates the readme to clarify that custom importers and functions are still experimental.
> Clarify custom importers and functions are still experimental

- package.json
This PR is the 3.0.0-beta.6 release.
With this release the I (@xzyfer) have become the new project lead for node-sass. I want to thank @am11 and the previous projects for their incredible work making node-sass what it is. I can only hope to do their work justice.
- updated to libSass 3.2.0-beta.6 (@xzyfer, #872)
- added a `--quiet` CLI flag (@paulcpederson, #841)
- added globbing support to the CLI (@paulcpederson, #828)
- improved documentation for experimental custom importers (@am11, #697)
- init libSass submodule when npm installing via git url (@xzyfer, #874)
- libuv segfaults with `render` (@saper, #713)
- typo in console output (@saper, #856)
- linting error (@andyshora, #842)
- improved error handling with `outFile` (@am11, #839)
- improved error handling for experimental custom …
> Release 3.0.0 beta.6

- scripts/install.js
Do not throw exception on invalid/mangled URL
Provide consistent error message with the URL
on all failures.
> Improve binary file download error handling

- lib/extensions.js
- package.json
This PR bumps package.json for 3.0.0.
:tada: :boom:
> Bump 3.0.0

- package.json
This PR bumps Libsass to 3.2.2.
> Bump Libsass to 3.2.3

- package.json
This PR bumps Libsass to 3.2.4.
> Bump Libsass to 3.2.4

- package.json
- Fixed ability to watch whole directory (#952, @kkopachev)
> Release v3.1.1

- appveyor.yml
We need this in order work around an issue with npm
https://github.com/npm/npm/issues/8517
> Lock to npm@2.7.5 in AppVeyor

- README.md
Removed an extra comma at line 345.
> Remove extra ',' in README

- TROUBLESHOOTING.md
- Use "npm install -ddd"
- Capture logfiles
- Provide known-good reference logfiles
for comparison
> TROUBLESHOOTING.md: Windows: Use "npm install -ddd"

- scripts/build.js
Might fix https://github.com/sass/node-sass/issues/1061
> Locate pangyp via module API

- README.md
https://github.com/hcatlin/libsass -> https://github.com/sass/libsass
> Use new libsass GitHub link

- scripts/install.js
> Add a hint for Chinese installers

- package.json
- test/spec.js
- test/util/index.js
This should hopefully be the final 3.4.0 beta.
> Bump LibSass to 3.3.0-beta3

- package.json
- src/binding.cpp
> Bump LibSass to 3.3.0

- scripts/build.js
Fixes https://github.com/sass/node-sass/issues/1301
> Use https:// to check out libsass code

- src/sass_types/boolean.cpp
- src/sass_types/color.cpp
- src/sass_types/factory.cpp
- src/sass_types/list.cpp
- src/sass_types/map.cpp
- src/sass_types/null.cpp
- src/sass_types/number.cpp
- src/sass_types/string.cpp
> Less V8 bureaucracy for Nan::ThrowTypeError

- CONTRIBUTING.md
- package.json
Updates the docs to help new contributors test any kind of bugfix.
Also, it adds the build script to package.json so that it can be run with `npm run-script build`
> Update contributing docs.

- test/util/index.js
Fix false positive when spec has a subfolder called error.
> Fix detection of error specs

- README.md
> Fix CLI usage

- package.json
Bump LibSass to 3.3.4
Fixes #1397 
Fixes #1346
Fixes #1329
> Bump LibSass to 3.3.4

- bin/node-sass
> Add more detailed usage examples to cli --help

- package.json
- src/libsass.gyp
~~This isn't the final LibSass 3.3.5 SHA1, but it's close.~~
~~I'll be using the branch in my CITGM.~~
> Bump LibSass 3.3.5

- scripts/build.js
> Fix script/build.js logic

- .travis.yml
> Add Node 6 config to Travis

- README.md
The support was added in sass/node-sass#1499
> README: Add Node.js 6 to supported versions.

- TROUBLESHOOTING.md
Added some additions to #1586. Looks like there's still some out of date information in the docs that will need to be addressed post release.
Closes #1586
> Fixes to troubleshooting doc

- ISSUE_TEMPLATE.md
Took the basic structure from Bootstrap since they have a large project that gets a lot of issues
Not sure if the last line is to harsh. I also dropped their part about pointing people to SO for basic questions.
> Update ISSUE_TEMPLATE with Bootstrap format

- README.md
Should be --sass-binary-site instead of --SASS_BINARY_SITE
> Fix process argument binary configuration example

- README.md
> Update supported node versions

- test/binding.js
> Fix binding tests leaking process values

- scripts/build.js
- scripts/install.js
Looks the default of stderr is causing issue for some CI servers.
Fixes #1801
> Send npmlog to stdout

- .travis.yml
Testing this out before PR'ing to master
> Add Coverity config to Travis

- .travis.yml
> Chore: Add back Node 7 to Travis

- appveyor.yml
> Chore: Add Node 8 to Appveyor

- package.json
- fixes issues with transitive dependency scss-tokenizer
- allows graph to follow symlinks
> Bump sass-graph@2.2.4

- README.md
> docs: Replace VS 2013 requirement with node-gyp

- TROUBLESHOOTING.md
To make this a little more discoverable.
Related #2035
> chore: add NPM 5 troubleshooting

- README.md
Fix the link target of the anchor of `functions section`.
> Readme:  Fix the broken anchor

- README.md
I improved the grammar used in some parts of this project's README. I also improved the clarity/accuracy of the info given on some sentences.
> Improved the grammar and clarity of the instructions in this project's README

- bin/node-sass
- lib/watcher.js
- test/fixtures/watcher/main/partials/_one.scss
- test/fixtures/watcher/main/partials/_two.scss
- test/fixtures/watcher/main/three.scss
- test/fixtures/watcher/main/two.scss
- test/watcher.js
Currently changes to non-partials are being picked up. This PR fixes
that and adds addition test coverage.
Fixes #2139
> Fix watching of entry points

- src/libsass/.editorconfig
> (editorconfig) s/spaces/space/

- README.md
I changed my GitHub username this evening and saw you had it referenced in the README
> docs: updated @10xLaCroixDrinker's username

- .github/ISSUE_TEMPLATE.md
Tired of closing these issues. It should be caught by the "search first", but alternatively we could just add it to the Readme
> Add note about bumping Request

- lib/index.js
- package.json
- test/spec.js
> [v5] Drop lodash.assign in favor of the native Object.assign

- bin/node-sass
- lib/render.js
This is an extension of #2268. Catches a few places missed the
first time around.
> Respect quiet option in Node API

- README.md
> Updates README.md with svg badge

- .github/PULL_REQUEST_TEMPLATE.md
Doesn't help those falling on the closed PRs, but might at least help those that read the PR template before submitting
> chore: Add link to 2355 on PR template

- TROUBLESHOOTING.md
Trying to see what common issues that we can include so if people search it'll come up in their first hits.
Still need to redo the table of contents
> [WIP] Troubleshooting edits

- .github/ISSUE_TEMPLATE/Bug_report.md
- CHANGELOG.md
- README.md
> Update references for v4.13 release

- README.md
Remove Unexpected token ) on the render example.
> Fix render example syntax

- .github/workflows/alpine.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- appveyor.yml
- test/types.js
Related to tracking issue https://github.com/sass/node-sass/issues/2972
> chore: Skip constructor tests on v14.6+

- .github/dependabot.yml
Re-submitting since #2997 got stuck. Likely from GitHub issue this afternoon
> chore: Add weekly DependaBot updates

- README.md
> Add a deprecation message to the readme

- package.json
Fixes #3293
reference: [CVE-2022-25758](https://github.com/advisories/GHSA-7mwh-4pqv-wmr8)
Regular expression denial of service in scss-tokenizer
> Bump sass-graph@^4.0.1
